development:  
  :concurrency: 5
production:  
  :concurrency: 6
:queues:
  - default
# :enabled: true
# :schedule:
#   reminder_queue:
#     every: ['3d', first_in: '120s']
#     class: ReminderQueueWorker